import { InjectionToken } from '@angular/core';
import { Product, TypeProduct } from '@herbalife/shared/models/products.model';

export const PRODUCTS: Array<Product> = [
  {
    id: 'formula_1_champignon',
    name: 'Formula 1 Champignon',
    quantity: 1,
    photo: 'champignon.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 59.5,
  },
  {
    id: 'formula_1_classic',
    name: 'Formula 1 Classique',
    quantity: 1,
    photo: 'formula_1_classic.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 54,
  },
  {
    id: 'formula_1_780',
    name: 'Formula 1 780g',
    quantity: 1,
    photo: 'formula_1_780.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 68,
  },
  {
    id: 'formula_1_bag',
    name: 'Formula 1 Sachet',
    quantity: 1,
    photo: 'formula_1_bag.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 20.5,
  },
  {
    id: 'tri_blend',
    name: 'Tri Blend',
    quantity: 1,
    photo: 'tri_blend.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 77.5,
  },
  {
    id: 'pro_20',
    name: 'Pro20',
    quantity: 1,
    photo: 'pro_20.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 71.5,
  },
  {
    id: 'chips',
    name: 'Chips',
    quantity: 1,
    photo: 'chips.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 23,
  },
  {
    id: 'protein bar',
    name: 'Barres protéinées',
    quantity: 1,
    photo: 'protein_bar.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 26.5,
  },
  {
    id: 'pdm',
    name: 'PDM',
    quantity: 1,
    photo: 'pdm.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 65,
  },
  {
    id: 'pdm_vegan',
    name: 'PDM Vegan',
    quantity: 1,
    photo: 'pdm_vegan.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 61.5,
  },
  {
    id: 'soybean',
    name: 'Graines de Soja',
    quantity: 1,
    photo: 'soybean.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 22,
  },
  {
    id: 'tomato_soup',
    name: 'Velouté de Tomate',
    quantity: 1,
    photo: 'tomato_soup.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 55.5,
  },
  {
    id: 'meal_bar',
    name: 'Barre repas',
    quantity: 1,
    photo: 'meal_bar.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 26.5,
  },
  {
    id: 'tea_50',
    name: 'Thé 50g',
    quantity: 1,
    photo: 'tea_50.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 35,
  },
  {
    id: 'tea_100',
    name: 'Thé 100g',
    quantity: 1,
    photo: 'tea_100.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 62.5,
  },
  {
    id: 'multi_fiber_drink',
    name: 'Boisson multifibres',
    quantity: 1,
    photo: 'multi_fiber_drink.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 37,
  },
  {
    id: 'microbiotic_max',
    name: 'Microbiotic Max',
    quantity: 1,
    photo: 'microbiotic_max.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 54.5,
  },
  {
    id: 'aloe',
    name: 'Aloe',
    quantity: 1,
    photo: 'alo.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 46,
  },
  {
    id: 'aloe_max',
    name: 'Aloe Max',
    quantity: 1,
    photo: 'alo_max.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 53,
  },
  {
    id: 'high_protein_iced_coffee',
    name: 'High Protein Iced Coffee',
    quantity: 1,
    photo: 'high_protein_iced_coffee.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 62.5,
  },
  {
    id: 'herbalifeline_max',
    name: 'Herbalifeline Max',
    quantity: 1,
    photo: 'herbalifeline_max.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 34.5,
  },
  {
    id: 'beta_heart',
    name: 'Beta Heart',
    quantity: 1,
    photo: 'beta_hurt.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 48.5,
  },
  {
    id: 'complete_thermo',
    name: 'Thermo complète',
    quantity: 1,
    photo: 'complete_thermo.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 54.5,
  },
  {
    id: 'nite_works',
    name: 'Niteworks',
    quantity: 1,
    photo: 'nite_works.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 96,
  },
  {
    id: 'complex_mineral',
    name: 'Minéral Complexe +',
    quantity: 1,
    photo: 'complex_mineral.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 35.5,
  },
  {
    id: 'formula_3',
    name: 'Formula 3',
    quantity: 1,
    photo: 'formula_3.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 41.5,
  },
  {
    id: 'immune_booster',
    name: 'Immune Booster',
    quantity: 1,
    photo: 'immune_booster.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 21.5,
  },
  {
    id: 'vitamines',
    name: 'Vitamines',
    quantity: 1,
    photo: 'vitamines.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 26.5,
  },
  {
    id: 'roseguard',
    name: 'Roseguard',
    quantity: 1,
    photo: 'roseguard.png',
    types: [TypeProduct.ALL, TypeProduct.INTERNAL_NUTRITION],
    price: 41,
  },
  {
    id: 'mask',
    name: 'Masque',
    quantity: 1,
    photo: 'mask.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 24,
  },
  {
    id: 'collagen_skin_booster',
    name: 'Collagen Skin Booster',
    quantity: 1,
    photo: 'collagen_skin_booster.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 73,
  },
  {
    id: 'tonic_lotion',
    name: 'Lotion Tonique',
    quantity: 1,
    photo: 'tonic_lotion.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 21.5,
  },
  {
    id: 'exfoliant',
    name: 'Exfoliant',
    quantity: 1,
    photo: 'exfoliant.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 22,
  },
  {
    id: 'try_kit',
    name: 'Kit essaie',
    quantity: 1,
    photo: 'try_kit.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 29.5,
  },
  {
    id: 'firming_eye_gel',
    name: 'Gel fermeté contour des yeux',
    quantity: 1,
    photo: 'firming_eye_gel.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 44.5,
  },
  {
    id: 'washing',
    name: 'Nettoyant',
    quantity: 1,
    photo: 'washing.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 28,
  },
  {
    id: 'day_night_uv_moisturizer',
    name: 'Crème hydratante jour/nuit/ UV',
    quantity: 1,
    photo: 'day_night_uv_moisturizer.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 55,
  },
  {
    id: 'liquid_soap',
    name: 'Savon liquide',
    quantity: 1,
    photo: 'liquid_soap.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 15.5,
  },
  {
    id: 'hand_body_cream',
    name: 'Crème mains et corps',
    quantity: 1,
    photo: 'hand_body_cream.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 15.5,
  },
  {
    id: 'conditioner',
    name: 'Après Shampoing',
    quantity: 1,
    photo: 'conditioner.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 15.5,
  },
  {
    id: 'shampoo',
    name: 'Shampoing',
    quantity: 1,
    photo: 'shampoo.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 15.5,
  },
  {
    id: 'soothing_gel',
    name: 'Gel apaisant',
    quantity: 1,
    photo: 'soothing_gel.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 15.5,
  },
  {
    id: 'bar_soap',
    name: 'Pain de savon',
    quantity: 1,
    photo: 'bar_soap.png',
    types: [TypeProduct.ALL, TypeProduct.EXTERNAL_NUTRITION],
    price: 10.5,
  },
  {
    id: 'cr7_bag',
    name: 'CR7 Sachet',
    quantity: 1,
    photo: 'cr7_bag.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 14,
  },
  {
    id: 'cr7_box',
    name: 'CR7 Boite',
    quantity: 1,
    photo: 'cr7_box.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 23.5,
  },
  {
    id: 'hidrate_h24',
    name: 'H24 Hydrate',
    quantity: 1,
    photo: 'hidrate_h24.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 50.5,
  },
  {
    id: 'prolong_h24',
    name: 'H24 Prolong',
    quantity: 1,
    photo: 'prolong_h24.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 69.5,
  },
  {
    id: 'endurance_h24',
    name: 'H24 Endurance',
    quantity: 1,
    photo: 'endurance_h24.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 100,
  },
  {
    id: 'strenght_24',
    name: 'H24 Strength',
    quantity: 1,
    photo: 'strenght_24.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 71,
  },
  {
    id: 'restore_24',
    name: 'H24 Restore',
    quantity: 1,
    photo: 'restore_24.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 46,
  },
  {
    id: 'liftoff',
    name: 'Liftoff',
    quantity: 1,
    photo: 'liftoff.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 33.5,
  },
  {
    id: 'guarana',
    name: 'Guarana',
    quantity: 1,
    photo: 'guarana.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 29,
  },
  {
    id: 'sport_formula_1',
    name: 'Formula 1 Sport',
    quantity: 1,
    photo: 'sport_formula_1.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 70.5,
  },
  {
    id: 'achieve_h24',
    name: 'Achieve H24',
    quantity: 1,
    photo: 'achieve_h24.png',
    types: [TypeProduct.ALL, TypeProduct.SPORT],
    price: 24,
  },
];

export const PRODUCT_PROVIDER = new InjectionToken<Array<Product>>('PRODUCTS');
